### ISSUE TITLE
`is_magical` for variables that have magic?

### ISSUE THREAD

**Issue by xsawyerx** [p5pclub/ref-util#7]
Variables that aren't references fail on all Ref::Util functions (because it isn't a reference), but having a simple function to check if something has magic or not.

I'm not sure it's useful though, or if it fits Ref::Util.

@plicease, @ilmari, what do you think?

**Comment by plicease** [comment]
I probably wouldn't use it often.

**Comment by xsawyerx** [comment]
@kaoru, have you some thoughts on this?

**Comment by kaoru** [comment]
@xsawyerx thinking about it, I don't think I'd use it often either. It doesn't solve the Readonly::XS issue because `is_hashref()` still wouldn't return true for something that returns true for `ref $_ eq ref {}`, and it wouldn't be safe to do `is_magical($_) || is_hashref($_)` as the check.

I think the Readonly::XS case just warrants some documentation warning that the two moduels don't play nicely with one another.

**Comment by xsawyerx** [comment]
@kaoru Thank you for the feedback.

The latest version details this problem.

I'm thus closing this issue. :)
